spring:
  datasource:
    url: jdbc:h2:file:./target/database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  web:
    resources:
      static-locations: "classpath:/static"
  jpa:
    hibernate:
      ddl-auto: update
